# 01 - Data Ingestion

**Objective:** Load the Wine dataset from raw files, clean, encode the target (3 classes), and save processed data.

**Dataset:** UCI Wine Recognition — 178 samples, 13 features, 3-class target (cultivar_1 / cultivar_2 / cultivar_3)

**Steps:**
1. Load raw data from CSV
2. Encode target as 0/1/2
3. Check data quality (missing values, dtypes)
4. Save processed data

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

print("Libraries imported successfully")

Libraries imported successfully

### Dataset Attributes

Understanding each column helps you make better decisions during cleaning and feature engineering.

The Wine dataset contains 13 chemical analysis measurements of wines from 3 different cultivars in Italy:

| # | Attribute | Description |
|---|-----------|-------------|
| 1 | **alcohol** | Alcohol content (% by volume). Typically ranges 11–15%. |
| 2 | **malic_acid** | Malic acid (g/L). An organic acid found in grapes; higher in cooler climates. |
| 3 | **ash** | Ash content (g/L). Inorganic residue after combustion; reflects mineral content. |
| 4 | **alcalinity_of_ash** | Alcalinity of ash (mEq/L). Measures the alkaline earth metals in ash. |
| 5 | **magnesium** | Magnesium (mg/L). An essential mineral; varies by soil and cultivar. |
| 6 | **total_phenols** | Total phenols. Antioxidant compounds; contribute to color, flavor, and mouthfeel. |
| 7 | **flavanoids** | Flavanoids. A subclass of phenols; major contributor to red wine color and taste. |
| 8 | **nonflavanoid_phenols** | Nonflavanoid phenols. Phenolic compounds that are not flavanoids. |
| 9 | **proanthocyanins** | Proanthocyanins. Tannin-like compounds; affect astringency. |
| 10 | **color_intensity** | Color intensity. Optical density measurement; indicates wine richness. |
| 11 | **hue** | Hue. Ratio of optical densities at different wavelengths; indicates wine age/type. |
| 12 | **od280_od315** | OD280/OD315 of diluted wines. Protein content indicator via UV absorption ratio. |
| 13 | **proline** | Proline (mg/L). An amino acid; higher in wines from warmer/drier regions. |

- **class** (target): Wine cultivar — 1, 2, or 3 (encoded as 0, 1, 2 for modeling)
  - Class 1 (cultivar_1): 59 samples
  - Class 2 (cultivar_2): 71 samples  
  - Class 3 (cultivar_3): 48 samples

In [2]:
# TODO: Load the raw CSV data into a DataFrame
# The wine.data file has no header row, so we pass header=None and assign column names ourselves.
# The first column is the class identifier (1-3), followed by 13 chemical measurements.

RAW_DIR = Path("../data/raw")

attribute_names = [
    "class", "alcohol", "malic_acid", "ash", "alcalinity_of_ash",
    "magnesium", "total_phenols", "flavanoids", "nonflavanoid_phenols",
    "proanthocyanins", "color_intensity", "hue", "od280_od315", "proline"
]

# Load the data with pd.read_csv()
# Use header=None and names=attribute_names.
# After loading, check the shape and preview the first few rows.
# Also run .info() to confirm all numeric columns have appropriate dtypes.

df = pd.read_csv(RAW_DIR / "wine.data", header=None, names=attribute_names)
print(f"Shape: {df.shape}")
print(df.head())
df.info()

Shape: (178, 14)
   class  alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  \
0      1    14.23        1.71  2.43               15.6        127
1      1    13.20        1.78  2.14               11.2        100
2      1    13.16        2.36  2.67               18.6        101
3      1    14.37        1.95  2.50               16.8        113
4      1    13.24        2.59  2.87               21.0        118

   total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
0           2.80        3.06                  0.28             2.29
1           2.65        2.76                  0.26             1.28
2           2.80        3.24                  0.30             2.81
3           3.85        3.49                  0.24             2.18
4           2.80        2.69                  0.39             1.82

   color_intensity   hue  od280_od315  proline
0             5.64  1.04         3.92     1065
1             4.38  1.05         3.40     1050
2             5.68  1.03         3.17     1185
3             7.80  0.86         3.45     1480
4             4.32  1.04         2.93      735
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   class                 178 non-null    int64
 1   alcohol               178 non-null    float64
 2   malic_acid            178 non-null    float64
 3   ash                   178 non-null    float64
 4   alcalinity_of_ash     178 non-null    float64
 5   magnesium             178 non-null    int64
 6   total_phenols         178 non-null    float64
 7   flavanoids            178 non-null    float64
 8   nonflavanoid_phenols  178 non-null    float64
 9   proanthocyanins       178 non-null    float64
 10  color_intensity       178 non-null    float64
 11  hue                   178 non-null    float64
 12  od280_od315           178 non-null    float64
 13  proline               178 non-null    int64
dtypes: float64(11), int64(3)
memory usage: 19.6 KB

In [3]:
# TODO: Encode the target variable as integers (0, 1, 2)
# The class column has three unique values: 1, 2, 3 (wine cultivars).
# We map these to 0, 1, 2 so models can process them with zero-indexed classes.
# Label encoding (0/1/2) is fine here because the classes have no ordinal relationship
# — any order works for a 3-class classifier that uses softmax.

# Example encoding logic:
# class_mapping = {1: 0, 2: 1, 3: 2}
# df["class"] = df["class"].map(class_mapping)

# TODO: Check the class distribution
# The dataset has 59/71/48 samples per class — verify this stayed correct after encoding.

In [4]:
# Encode target: map class 1,2,3 → 0,1,2
class_mapping = {1: 0, 2: 1, 3: 2}
df["class"] = df["class"].map(class_mapping)

# Verify encoding
print("Unique classes after encoding:", df["class"].unique())
print("\nClass distribution:")
print(df["class"].value_counts().sort_index())

Unique classes after encoding: [0 1 2]

Class distribution:
class
0    59
1    71
2    48
Name: count, dtype: int64

In [5]:
# TODO: Use .value_counts() to check the distribution of the encoded classes

In [6]:
# Check class distribution with value_counts
print("Class distribution (value_counts):")
print(df["class"].value_counts().sort_index())
print(f"\nTotal samples: {len(df)}")
print(f"Class balance: {df['class'].value_counts(normalize=True).sort_index().round(3).to_dict()}")

Class distribution (value_counts):
class
0    59
1    71
2    48
Name: count, dtype: int64

Total samples: 178
Class balance: {0: 0.331, 1: 0.399, 2: 0.27}

In [7]:
# TODO: Check for missing values in each column
# Use df.isnull().sum() to get a count of NaN entries per column.
# The original wine.data has no missing values, but it's good practice to verify.


# TODO: Handle missing values if any are found
# Two common strategies:
#   - df.dropna() — removes any row with a missing value (simple, but you lose data)
#   - df.fillna(value) — replaces missing entries with something like the column mean or median
# Choose the approach that makes sense for your data.

# TODO: Verify the final data is clean using df.info() and df.describe()

In [8]:
# Check for missing values
print("Missing values per column:")
missing = df.isnull().sum()
print(missing)
print(f"\nTotal missing values: {missing.sum()}")

# If any missing values exist, handle them
if missing.sum() > 0:
    # Strategy: fill numeric columns with median (robust to outliers)
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())
    print("\nMissing values filled with column medians.")
else:
    print("\nNo missing values found — data is complete.")

# Verify data is clean
print("\n--- Data Summary ---")
df.info()
print("\n--- Descriptive Statistics ---")
df.describe()

Missing values per column:
class                   0
alcohol                 0
malic_acid              0
ash                     0
alcalinity_of_ash       0
magnesium               0
total_phenols           0
flavanoids              0
nonflavanoid_phenols    0
proanthocyanins         0
color_intensity         0
hue                     0
od280_od315             0
proline                 0
dtype: int64

Total missing values: 0

No missing values found — data is complete.

--- Data Summary ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   class                 178 non-null    int64
 1   alcohol               178 non-null    float64
 2   malic_acid            178 non-null    float64
 3   ash                   178 non-null    float64
 4   alcalinity_of_ash     178 non-null    float64
 5   magnesium             178 non-null    int64
 6   total_phenols         178 non-null    float64
 7   flavanoids            178 non-null    float64
 8   nonflavanoid_phenols  178 non-null    float64
 9   proanthocyanins       178 non-null    float64
 10  color_intensity       178 non-null    float64
 11  hue                   178 non-null    float64
 12  od280_od315           178 non-null    float64
 13  proline               178 non-null    int64
dtypes: float64(11), int64(3)
memory usage: 19.6 KB

--- Descriptive Statistics ---

,class,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280_od315,proline
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,0.938202,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258
std,0.775035,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474
min,0.000000,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000
25%,0.000000,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000
50%,1.000000,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000
75%,2.000000,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000
max,2.000000,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000

In [9]:
# TODO: Drop any irrelevant columns that won't be used for modeling (if any)
# For example, if there are columns that are just identifiers or have too many unique values, they might not be useful for prediction and could be dropped to simplify the dataset.
# df.drop(columns=["Irrelevant_Column"], inplace=True) #

In [10]:
# No irrelevant columns to drop in the Wine dataset.
# All 13 features are chemical measurements useful for classification.
# The "class" column is our target variable — keep it.
print(f"Columns ({len(df.columns)}): {df.columns.tolist()}")
print("No columns dropped — all are relevant for modeling.")

Columns (14): ['class', 'alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280_od315', 'proline']
No columns dropped — all are relevant for modeling.

In [11]:
# TODO: Change column names to be more Pythonic (optional but recommended) - data specific. 
# For example, if you have a column named "Temperature(°C)", you might want to rename it to "temperature_c" for easier access in code.
# df.rename(columns={"Temperature(°C)": "temperature_c"}, inplace=True)

In [12]:
# Column names are already Pythonic (snake_case, no special characters).
# We defined them ourselves when loading the CSV with header=None.
print("Current column names:")
for i, col in enumerate(df.columns, 1):
    print(f"  {i:2d}. {col}")
print("\nNo renaming needed — names are already clean and Pythonic.")

Current column names:
   1. class
   2. alcohol
   3. malic_acid
   4. ash
   5. alcalinity_of_ash
   6. magnesium
   7. total_phenols
   8. flavanoids
   9. nonflavanoid_phenols
  10. proanthocyanins
  11. color_intensity
  12. hue
  13. od280_od315
  14. proline

No renaming needed — names are already clean and Pythonic.

In [13]:
# TODO: Find duplicate rows in the DataFrame
# Use df.duplicated() to identify duplicate rows. 
# This returns a boolean Series where True indicates a duplicate row (except for the first occurrence).
# You can sum this Series to get the total count of duplicates.


# TODO: Duplicates can be searched for across all columns or a subset of columns.
# e.g. df.duplicated(subset=["Date", "Hour"])

# TODO: Remove duplicate rows if any are found
# Use df.drop_duplicates() to remove duplicate rows.
# param: keep="first": it keeps the first occurrence and drops subsequent duplicates. alternatives are "last" (keeps the last occurrence) or False (drops all duplicates).
# You can specify subset=["Date", "Hour"] to drop duplicates based on just those columns.

# TODO: Alternatively, you can use df.duplicated() to filter the DataFrame and inspect duplicates before dropping them.

# TODO: Reset the index after dropping duplicates

In [14]:
# Find duplicate rows
duplicates = df.duplicated()
num_duplicates = duplicates.sum()
print(f"Number of duplicate rows: {num_duplicates}")

if num_duplicates > 0:
    # Inspect duplicates before dropping
    print("\nDuplicate rows:")
    print(df[duplicates])
    
    # Remove duplicates, keep the first occurrence
    df = df.drop_duplicates(keep="first")
    print(f"\nAfter removing duplicates: {df.shape[0]} rows remaining")
    
    # Reset index
    df = df.reset_index(drop=True)
    print("Index reset.")
else:
    print("No duplicates found — all rows are unique.")

print(f"\nFinal shape: {df.shape}")

Number of duplicate rows: 0
No duplicates found — all rows are unique.

Final shape: (178, 14)

In [15]:
# TODO: Save the processed data to data/processed/clean_data.csv
# Use df.to_csv() with index=False so we don't write the DataFrame index as a column.

PROCESSED_DIR = Path("../data/processed")
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

# df.to_csv(PROCESSED_DIR / "clean_data.csv", index=False)
# print("Clean data saved successfully")

In [16]:
# Save the processed data
PROCESSED_DIR = Path("../data/processed")
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

df.to_csv(PROCESSED_DIR / "clean_data.csv", index=False)
print(f"Clean data saved to: {PROCESSED_DIR / 'clean_data.csv'}")
print(f"Shape: {df.shape}")

Clean data saved to: ..\data\processed\clean_data.csv
Shape: (178, 14)

In [17]:
# TODO: Verify the saved file by loading it back into a new DataFrame
# This step confirms the file wasn't corrupted during the write process.
# Compare the shape of the loaded data to the original shape.

# df_check = pd.read_csv(PROCESSED_DIR / "clean_data.csv")
# print(f"Loaded data shape: {df_check.shape}")
# assert df_check.shape == df.shape, "Shape mismatch after save-load cycle"
# print("Verification passed: data round-trips correctly")

In [18]:
# Verify the saved file by loading it back
df_check = pd.read_csv(PROCESSED_DIR / "clean_data.csv")
print(f"Loaded data shape: {df_check.shape}")
assert df_check.shape == df.shape, "Shape mismatch after save-load cycle"
print("Verification passed: data round-trips correctly")
print(f"\nFirst 3 rows of reloaded data:")
print(df_check.head(3))

Loaded data shape: (178, 14)
Verification passed: data round-trips correctly

First 3 rows of reloaded data:
   class  alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  \
0      0    14.23        1.71  2.43               15.6        127
1      0    13.20        1.78  2.14               11.2        100
2      0    13.16        2.36  2.67               18.6        101

   total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
0           2.80        3.06                  0.28             2.29
1           2.65        2.76                  0.26             1.28
2           2.80        3.24                  0.30             2.81

   color_intensity   hue  od280_od315  proline
0             5.64  1.04         3.92     1065
1             4.38  1.05         3.40     1050
2             5.68  1.03         3.17     1185

## 2. Relational Data — Joining Tables (NOT USED FOR DATA ANALYSIS)

In real-world projects, data is rarely handed to you in a single tidy CSV. 
It is often spread across multiple tables in a database — a **fact** table 
and several **dimension** tables, linked by key columns.

To build your feature matrix you need to **join** these tables back together.

In this section you will work with a relational version of the Wine data,
split into multiple CSV files that simulate a database:

| File | Content | Key column |
|------|---------|------------|
| `cultivar.csv` | Cultivar class label | `sample_id` |
| `chemical.csv` | Chemical measurements | `chemical_id` |
| `phenols.csv` | Phenol-related measurements | `phenol_id` |

Some IDs appear in only some tables — exactly like a real database where 
certain measurements were not recorded or have extra lab entries. 
Your job is to re-assemble the full dataset.

In [19]:
# Load the relational tables (if available)
RELATIONAL_DIR = Path("../data/raw/relational")

# TODO: Load relational CSV files if they exist for the wine dataset
# cultivar = pd.read_csv(RELATIONAL_DIR / "cultivar.csv")
# chemical = pd.read_csv(RELATIONAL_DIR / "chemical.csv")
# phenols = pd.read_csv(RELATIONAL_DIR / "phenols.csv")

# TODO: Inspect each table
# Check the shape and first few rows.
# How many IDs does each table have? Are the ID ranges the same?

# print(f"Cultivar: {cultivar.shape}")
# print(f"Chemical: {chemical.shape}")
# print(f"Phenols: {phenols.shape}")

In [20]:
# Load relational tables
RELATIONAL_DIR = Path("../data/raw/relational")

cultivar = pd.read_csv(RELATIONAL_DIR / "cultivar.csv")
chemical = pd.read_csv(RELATIONAL_DIR / "chemical.csv")
phenols = pd.read_csv(RELATIONAL_DIR / "phenols.csv")

# Inspect each table
print(f"Cultivar: {cultivar.shape}")
print(cultivar.head())
print(f"\nChemical: {chemical.shape}")
print(chemical.columns.tolist())
print(chemical.head())
print(f"\nPhenols: {phenols.shape}")
print(phenols.columns.tolist())
print(phenols.head())

Cultivar: (178, 2)
   sample_id  class
0          1      0
1          2      0
2          3      0
3          4      0
4          5      0

Chemical: (176, 8)
['chemical_id', 'alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'color_intensity', 'proline']
   chemical_id  alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  \
0            1    14.23        1.71  2.43               15.6      127.0
1            2    13.20        1.78  2.14               11.2      100.0
2            3    13.16        2.36  2.67               18.6      101.0
3            4    14.37        1.95  2.50               16.8      113.0
4            5    13.24        2.59  2.87               21.0      118.0

   color_intensity  proline
0             5.64   1065.0
1             4.38   1050.0
2             5.68   1185.0
3             7.80   1480.0
4             4.32    735.0

Phenols: (175, 7)
['phenol_id', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'hue', 'od280_od315']
   phenol_id  total_phenols  flavanoids  nonflavanoid_phenols  \
0          1           2.80        3.06                  0.28
1          2           2.65        2.76                  0.26
2          3           2.80        3.24                  0.30
3          4           3.85        3.49                  0.24
4          5           2.80        2.69                  0.39

   proanthocyanins   hue  od280_od315
0             2.29  1.04         3.92
1             1.28  1.05         3.40
2             2.81  1.03         3.17
3             2.18  0.86         3.45
4             1.82  1.04         2.93

In [21]:
# TODO: Merge cultivar with chemical measurements
# Use pd.merge() with left_on="sample_id" and right_on="chemical_id".
# Use a LEFT JOIN to keep all specimens.
# Count how many rows have NaN for chemical columns.

# merged = pd.merge(cultivar, chemical, left_on="sample_id", right_on="chemical_id", how="left")

# TODO: Now try an INNER JOIN. How many rows do you lose? Why?

In [22]:
# LEFT JOIN: Merge cultivar with chemical measurements
merged = pd.merge(cultivar, chemical, left_on="sample_id", right_on="chemical_id", how="left")
print(f"After LEFT JOIN (cultivar + chemical): {merged.shape}")

# Count rows with missing chemical data
chemical_cols = ["alcohol", "malic_acid", "ash", "alcalinity_of_ash", "magnesium", "color_intensity", "proline"]
missing_chemical = merged[chemical_cols].isna().any(axis=1).sum()
print(f"Rows missing chemical data: {missing_chemical}")

# INNER JOIN comparison
merged_inner = pd.merge(cultivar, chemical, left_on="sample_id", right_on="chemical_id", how="inner")
print(f"\nAfter INNER JOIN (cultivar + chemical): {merged_inner.shape}")
print(f"Rows lost with INNER JOIN: {len(cultivar) - len(merged_inner)}")

After LEFT JOIN (cultivar + chemical): (178, 10)
Rows missing chemical data: 5

After INNER JOIN (cultivar + chemical): (173, 10)
Rows lost with INNER JOIN: 5

In [23]:
# TODO: Merge in the phenol measurements
# Chain a second merge to bring in phenol data.

# TODO: Check how many rows are missing phenol data

In [24]:
# Merge in phenol measurements (chain second merge)
merged = pd.merge(merged, phenols, left_on="sample_id", right_on="phenol_id", how="left")
print(f"After LEFT JOIN (+ phenols): {merged.shape}")

# Count rows missing phenol data
phenol_cols = ["total_phenols", "flavanoids", "nonflavanoid_phenols", "proanthocyanins", "hue", "od280_od315"]
missing_phenols = merged[phenol_cols].isna().any(axis=1).sum()
print(f"Rows missing phenol data: {missing_phenols}")

# Show columns in final merged table
print(f"\nAll columns: {merged.columns.tolist()}")
print(f"\nFirst few rows:")
merged.head()

After LEFT JOIN (+ phenols): (178, 17)
Rows missing phenol data: 8

All columns: ['sample_id', 'class', 'chemical_id', 'alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'color_intensity', 'proline', 'phenol_id', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'hue', 'od280_od315']

First few rows:

,sample_id,class,chemical_id,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,color_intensity,proline,phenol_id,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,hue,od280_od315
0,1,0,1.0,14.23,1.71,2.43,15.6,127.0,5.64,1065.0,1.0,2.80,3.06,0.28,2.29,1.04,3.92
1,2,0,2.0,13.20,1.78,2.14,11.2,100.0,4.38,1050.0,2.0,2.65,2.76,0.26,1.28,1.05,3.40
2,3,0,3.0,13.16,2.36,2.67,18.6,101.0,5.68,1185.0,3.0,2.80,3.24,0.30,2.81,1.03,3.17
3,4,0,4.0,14.37,1.95,2.50,16.8,113.0,7.80,1480.0,4.0,3.85,3.49,0.24,2.18,0.86,3.45
4,5,0,5.0,13.24,2.59,2.87,21.0,118.0,4.32,735.0,5.0,2.80,2.69,0.39,1.82,1.04,2.93

In [25]:
# TODO: Compare to the original single-table shape
# The original wine.data has 178 rows with 13 features + class.
# After splitting and rejoining, how many complete rows do you have?

# HINT: This tells you how many specimens have all data sources.

In [26]:
# Compare to the original single-table shape
print(f"Original wine.data: {df.shape} (178 rows × 14 columns incl. class)")
print(f"Merged relational:  {merged.shape}")

# Count complete rows (no NaN in any feature column)
all_feature_cols = chemical_cols + phenol_cols
complete_rows = merged.dropna(subset=all_feature_cols)
print(f"\nComplete rows (all features present): {len(complete_rows)} / {len(merged)}")
print(f"Rows with at least one missing feature: {len(merged) - len(complete_rows)}")

# Check if any row is missing BOTH chemical and phenol data
both_missing = (merged[chemical_cols].isna().any(axis=1) & merged[phenol_cols].isna().any(axis=1)).sum()
print(f"Rows missing data from BOTH tables: {both_missing}")

Original wine.data: (178, 14) (178 rows × 14 columns incl. class)
Merged relational:  (178, 17)

Complete rows (all features present): 165 / 178
Rows with at least one missing feature: 13
Rows missing data from BOTH tables: 0

### Exercises

1. **Label encoding vs one-hot**: We used `.map({...})` to encode 3 classes as 0/1/2. Would `pd.get_dummies()` work too? When might one-hot encoding a target variable cause problems? (HINT: Think about how softmax or distance-based models interpret the target.)
2. **Which JOIN?**: You used LEFT JOINs above. Replace them with INNER JOINs. How many rows do you lose overall? Why?
3. **Missing value experiment**: Intentionally introduce NaN with `df.loc[0:4, "alcohol"] = np.nan`. Compare `dropna()` vs `fillna(df["alcohol"].mean())`. How does each strategy affect the shape and the class distribution?
4. **Feature engineering**: Create `phenol_ratio = flavanoids / total_phenols` and `color_hue_product = color_intensity * hue`. Use `groupby("class")[["phenol_ratio", "color_hue_product"]].describe()`. Do these composite features separate the classes better than the raw measurements?
5. **Merge on the wrong key**: Try merging tables on `class` instead of ID. What happens to the row count? Why is this dangerous?
6. **Save the reloaded version**: After merging all tables back, save the result to `data/processed/clean_data.csv`. Verify the shape matches the original.
7. **What would break?**: If `wine.data` had a header row (column names as the first line of data), which cell would fail first? What error would it produce? How would you fix it?